### ISSUE TITLE
generalization ability on other different  cameras layout setting

### ISSUE THREAD

**Issue by guker** [facebookresearch/UmeTrack#5]
I have a question about umetrack's generalization ability on other cameras layout.   in other words，  if i change the 
relative position between cameras,  such as quest 2 vs quest pro that have different cameras layout setting,  can it works ？@shchhan-meta

**Comment by shchhan-meta** [comment]
For the pretrained model, we haven't done such test. So we don't have a clear answer. The network architecture itself does allow mixing data from different camera layouts without any compromising the metrics. And this is mainly because of the FTL layer that tries to encourage equivariant features from the network.

**Comment by guker** [comment]
> For the pretrained model, we haven't done such test. So we don't have a clear answer. The network architecture itself does allow mixing data from different camera layouts without any compromising the metrics. And this is mainly because of the FTL layer that tries to encourage equivariant features from the network.

thanks for your answer.  "The network architecture itself does allow mixing data from different cameras layouts"  mean that you trained umetrack model using different camera layout data  in training phase?

**Comment by shchhan-meta** [comment]
To clarify, the pre-trained model in this repo is strictly trained on the dataset available in this repo. No extra data is used. The camera layout in this project is similar to the Quest camera layout. And we haven't validated whether this pre-trained model works on other camera layout.

Inside Meta, we've been mixing data from different camera layouts to achieve generalization across devices. This approach worked well for us. But we are not able to release the data from the other camera layouts.

**Comment by pablovela5620** [comment]
is the detection model used the same one described in the Megatrack paper? I know theres an unofficial implementation [here](https://github.com/milkcat0904/MegaTrack-pytorch), is there any plans to release an official implementation?

**Comment by shchhan-meta** [comment]
We did use the same detection model as the MegaTrack paper. We currently don't have any plan to release the detection model.
