### ISSUE TITLE
Question about Hand ROI

### ISSUE THREAD

**Issue by cmfcm** [facebookresearch/UmeTrack#7]
Hi,
After reading the paper, I have some questions about how to obtain the hand ROI during inference time. I noticed that you mentioned in the paper that:
> At inference time when ground truth is not available, we rely on the previously tracked pose to estimate the intrinsics matrix.

But how should we handle the situation when it is the first frame or when hand tracking is lost? Do we need another module to detect hand ROI in these cases(e.g. DetNet)?

**Comment by shchhan-meta** [comment]
@cmfcm , we do rely on a detection network which can predict the hand ROI. The detection network is separate from this paper and we didn't include its evaluations/code in this project.
